### ISSUE TITLE
⭐ Source Request, in streamplay ( allanime, anitaku, animepahe, kickassanime)

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/cloudstream-extensions-phisher#161]
- [ ] Allanime 
    - Lots of server
    - Re-upload anime to good server
    - fast server 
    - https://allmanga.to/anime
 

- [x] Anitaku 
   - No intro needed
   - Visual & subtitles are unmodified from torrent releases
   - https://anitaku.pe/home.html

- [x] Animepahe 
   - Low bandwidth use 
   - fast server 
   - Update and select the best video source/fansub release
   - it's like a indexing site, so it will be good in streamplay 
   - https://animepahe.ru/

- [ ] Kickassanime 
   - Highest video quality ( high bitrate )
   - good for person who want high quality 
   - https://kickassanimes.io/
   

They have more alternative sites/ proxy site, so cloudflare wouldn't be a issue 

English repo have allanime and animepahe plugin, you can get code from there ( now they are disabled/not working)

Rowdy have anitaku 

Thanks ( didn't used source request, because had to type a lot more, I had tried to do this there but doesn't liked it )

**Comment by phisher98** [comment]
As of now 2 Sources can be added due to limitations of API

**Comment by Krishna-art-dev** [comment]
> As of now 2 Sources can be added due to limitations of API

No problem, but if you can then add them, as they have pros for certain type of user and for certain type of content
