### ISSUE TITLE
Repo link changed ( do we have to change it now? )

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/cloudstream-extensions-phisher#174]

**Comment by phisher98** [comment]
Yeah but if you already have extension installed then no but i have also pushed to megarepo to be changed

Manual add
https://raw.githubusercontent.com/phisher98/cloudstream-extensions-phisher/refs/heads/builds/repo.json

**Comment by Krishna-art-dev** [comment]
> Yeah but if you already have extension installed then no but i have also pushed to megarepo to be changed
> 
> Manual add https://raw.githubusercontent.com/phisher98/cloudstream-extensions-phisher/refs/heads/builds/repo.json

I have installed your repo, but will that link get updates?
Or everyone have to update there link to new one?

**Comment by phisher98** [comment]
They will need to till i get Megarepo PR approved

**Comment by mpaunovic** [comment]
Is the shortcode still "Hindirepo" or has it been changed?

**Comment by phisher98** [comment]
Short code : phisherrepo
