### ISSUE TITLE
Streamplay ( no anime movie link ) 

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/cloudstream-extensions-phisher#175]
### Source Name

Streamplay 

### Source language

Sub dub 

### Steps to reproduce

Any anime movie, try blue lock 
Play it 
It doesn't get any links 

### Expected behavior

Streamplay should also find anime movies links

### Actual behavior

Doesn't return any anime movie link 

### CloudStream Version

Red icon ( latest )

### Other details

![Screenshot_2024-09-28-11-10-20-88_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/3b3d5cf8-36ed-40b3-9475-fe7f2c19cac4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
That Movie is not available on Sources thats why

**Comment by phisher98** [comment]
Need to rework at Gogo as its only source i was able to find it

**Comment by phisher98** [comment]
This can't be fixed as most sources still dont contains this movie or if it did its complex to match 
Closing this

**Comment by Krishna-art-dev** [comment]
> This can't be fixed as most sources still dont contains this movie or if it did its complex to match Closing this

Not only that, I was searching one piece 3d 2y 

Hianime returned movie, animepahe and gogo also, ( using anicompat, but no results though stream play

**Comment by phisher98** [comment]
anicompat have Streamplay ? No right if they are working because they are seprate extensions

**Comment by Krishna-art-dev** [comment]
> anicompat have Streamplay ? No right if they are working because they are seprate extensions
> 
> try other anitaku from RowdyAvacado repo

Anicompat doesn't have streamplay 
They are working because they are separate extension made for only that website 
Used animepahe from anicompat

**Comment by phisher98** [comment]
Thats what i am saying Streamplay have different way to fetch sources
