### ISSUE TITLE
Site Request: animekhor.org

### ISSUE THREAD

**Issue by N4KEDH0K4GE** [phisher98/cloudstream-extensions-phisher#176]
### Details

animekhor.org is a site that focuses on Chinese animations(Donghua) and the group stays on top of every release and is constantly updating their database. This would be a great addition as the app doesn’t have any extensions that focus on Donghua. If anyone is willing to take a look it would greatly appreciated.

I hope I did this correctly, thank you so much. I really appreciate you adding the site. Thank you! 😊 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Fulfilled
