### ISSUE TITLE
Wrong name of source in Streamplay.

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/cloudstream-extensions-phisher#177]
### Details

Genoanime is long gone. But in Streamplay there is a excellent source named as Genoanime, probably the naming is wrong.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Rachitidk** [comment]
![Screenshot_2024-09-28-21-30-03-67_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/d3a599ee-52ba-44d3-99f3-dad52da80ac3)

**Comment by phisher98** [comment]
[0557f75](https://github.com/phisher98/cloudstream-extensions-phisher/commit/0557f75a0b90a4898b96857b5f3ab68dc5165c6f)

Disabled Thanks for Reporting

**Comment by Rachitidk** [comment]
Hey, please bring it back, there was no need to disable that, that source provided anime in excellent quality, even the new one. I was just telling as Genoanime is no more how it is providing the anime still, so it thought it was some other provider with wrong naming.

**Comment by phisher98** [comment]
I was checking and it was just name and all other was same as Hianime so there will be no issues to remove it as it was same source

**Comment by Rachitidk** [comment]
![Screenshot_2024-09-29-13-26-57-77_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/852baf42-9f10-4852-b422-9cf2e3c63972)

Still there
