### ISSUE TITLE
Alternative to DhamerMovies maybe

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/cloudstream-extensions-phisher#178]
### Source name

idk

### Source link

https://a.datadiff.us.kg/

### Source language

Mainly english

### Other details

Probably Nsfw are there

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
I have added that but due to limitations of this source most of time it doesn't at all work so I have removed it

**Comment by nguyenquocngu93** [comment]
@phisher98 

Still work with me (vlc player)
Pls bring it back

**Comment by Rachitidk** [comment]
I wrote alternative meaning the construction is same not a proxy site to DhamerMovies. This is a different site and doesn't has limitations. Check for yourself. @phisher98

**Comment by phisher98** [comment]
Added back

**Comment by Rachitidk** [comment]
Thanks

**Comment by nguyenquocngu93** [comment]
![Screenshot_2024-09-29-16-44-18-576_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/07cdf786-9c19-451d-8e59-6a0ed43dcb39)

This is a feedback 
And Thank You.

**Comment by phisher98** [comment]
I thought it was dead so thats why i removed it Thanks for the feedback and suggestionb
