### ISSUE TITLE
Miruro

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/cloudstream-extensions-phisher#179]
### Source name

Miruro

### Source link

https://www.miruro.tv/

### Source language

English, Japanese

### Other details

Was voted the `best site in anime by crowd` : https://challonge.com/Anime_Streaming

![IMG_20240929_150538](https://github.com/user-attachments/assets/526c6c42-3d8e-47d3-929a-617d9a02beb4)

Other site like hianime and anitaku are excellent, but this offer other features such a `marking intro and outro for available for latest release` which other doesn't. Also the servers are very fast especially Zoro, Gogo.

![IMG_20240929_150332](https://github.com/user-attachments/assets/958b4930-3d59-4241-aa31-c96f685bdcf8)

If you can add both in Streamplay and as well as a seperate provider will be helpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
All of its Sources are Gogo and Hianime I have added Gogo and Zoro but didnt added Vidstream as its basically Hianime which is already added

**Comment by Rachitidk** [comment]
`Not working`

![Screenshot_2024-09-29-20-28-23-37_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/d0008d51-3957-4189-aa77-ebbacb0cd04e)


Also can you add this as all the previous one so preferred quality is at the top.

![IMG_20240929_203129](https://github.com/user-attachments/assets/f1985ad9-bd40-43e4-8496-45a35d7a440c)

also can you add this as all the previous one so preferred quality is at the top.
![Screenshot_2024-09-29-20-31-14-47_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/992cbf0f-ab58-41e9-aa39-eb6a493387c3)

**Comment by phisher98** [comment]
Only master is not working I will check on it otherwise other working

**Comment by Rachitidk** [comment]
> Only master is not working I will check on it otherwise other working

No, None are working, it was 1080p which I tried to play but it didn't worked and the error came and then it was passed down to the next server which was shown in screenshot.

**Comment by phisher98** [comment]
Have you tried same on website ? If it's not a extension issue source issue

**Comment by Rachitidk** [comment]
![IMG_20240929_223627](https://github.com/user-attachments/assets/81008b1f-108f-4d15-840f-02bf1f4ea89a)
Working on site.

**Comment by phisher98** [comment]
Its not available on Api right now

**Comment by Rachitidk** [comment]
> Its not available on Api right now

Oh I see. Np.
Thanks for it, it super fast maybe the fastest one in Streamplay.

Just curious, then how is it working on website?
