### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Politecoder** [phisher98/cloudstream-extensions-phisher#181]
https://github.com/user-attachments/assets/007c40f0-0a95-4702-8201-dfacd8162a7d

As you can see, it extracts all episode links from movies4u in 1 single episode, please fix it.

**Comment by phisher98** [comment]
As Told before when adding Series not supported for it

**Comment by Politecoder** [comment]
Ok no issues bro

**Comment by Politecoder** [comment]
Thank you
