### ISSUE TITLE
Fix Extensions Link 

### ISSUE THREAD

**Issue by Zafor7869** [phisher98/cloudstream-extensions-phisher#183]
### Details

![Screenshot_20241001_025323](https://github.com/user-attachments/assets/93403062-d8b3-4480-b214-e4d67e368c91)

Bro, please fix your extensions. When I try to add your link in another phone It shows empty and link not found. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Rachitidk** [comment]
Name has been changed, type phisher repo in new link.

**Comment by phisher98** [comment]
Use short code phisherrepo new name is Phisher repo
