### ISSUE TITLE
IPTV Sports 18

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/cloudstream-extensions-phisher#184]
### Details

![Screenshot_2024-10-01-09-32-33-33_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/ec6a4787-b534-4d34-98c9-532e6cdbe076)
Sports18 provider in Iptv was only for the first match, second match not streamed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Yes you need to create a issue if you want me add any link or stream and this was a match streaming link so it won't work now as match finished which match or channel you want me to add I will try to find it and add it

**Comment by Rachitidk** [comment]
India vs Bangladesh 2nd test.
Very Grateful.

**Comment by phisher98** [comment]
Added give it a Refresh or reload links sometime
