### ISSUE TITLE
Streamplay different different movies sources on different movie title 

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/cloudstream-extensions-phisher#185]
### Source Name

Streamplay 

### Source language

Hindi

### Steps to reproduce

https://jmp.sh/s/fNm3y3T29ia7CspzbjMw

Video 

### Expected behavior

Previously when I watched it on streamplay, it was alright all sources gave that leo movie that I was searching, but now all sources giving different movie

### Actual behavior

Different movies on different movie title 

And pixeldrain isn't working idk why, sometimes it work when playing movie from start, when I skip a lot of time, like 20-30 min it just stop working 

### CloudStream Version

Red icon ( latest )

### Other details

Pixeldrain and hubcloud is like hit or miss idk why, first time when opening any movie and playing that source works, but after closing and again playing that source doesn't work for me, it just shows that error 

Tried on streamplay at first it was playing, after closing and reopening cs3 it just shows error 

Same with saurabh's extension at first it plays then it doesn't, can't able to record it but it happens 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Yes for Leo and some titles it could be a issue because there are many title with same title and year which is not possible to differentate but its rarely happens

**Comment by Krishna-art-dev** [comment]
> Yes for Leo and some titles it could be a issue because there are many title with same title and year which is not possible to differentate but its rarely happens
> 
> This can't be fixed
> 
> ![image](https://private-user-images.githubusercontent.com/153359846/372371266-83e8698e-6b21-4397-8d28-9a55f7d52b48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3Njk4MTAsIm5iZiI6MTcyNzc2OTUxMCwicGF0aCI6Ii8xNTMzNTk4NDYvMzcyMzcxMjY2LTgzZTg2OThlLTZiMjEtNDM5Ny04ZDI4LTlhNTVmN2Q1MmI0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwNzU4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2EzYzYxNzAzZjRlMzYyZGNhYzFiYzU1ZTFkMzY2MzAzMzZhN2ZiZWI3YTA4YzQwOTk1MmRkNDE1NzU1ZGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rTO-1G-7YeBsU4b98VYO830zDXAF8DFAwgmeEIEFo04)

But before streamplay update, it was working fine, I had played movie before streamplay update

**Comment by Krishna-art-dev** [comment]
Before I remember all vega movies sources was available in streamplay, not it's less and different movies ones

**Comment by phisher98** [comment]
Its from Movies4u

**Comment by Krishna-art-dev** [comment]
> Its from Movies4u

Meaning?

**Comment by phisher98** [comment]
V cloud links are avaiable from this source as well

**Comment by Krishna-art-dev** [comment]
> V cloud links are avaiable from this source as well

Just a question 
Hub cloud and v-cloud are same?

Now streamplay working fine

**Comment by phisher98** [comment]
Yes Same with Different Name
