### ISSUE TITLE
Is it possible to add this site?

### ISSUE THREAD

**Issue by digitalus00** [phisher98/cloudstream-extensions-phisher#188]
### Source name

Yo Sin Tv

### Source link

https://www.yosin-tv.net/

### Source language

Multi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by Rachitidk** [comment]
I think no, as recaptcha is present.

**Comment by phisher98** [comment]
How long this source is up ?

**Comment by digitalus00** [comment]
I dont understand what are you talking but it will be good if you add.

**Comment by phisher98** [comment]
No
