### ISSUE TITLE
It is possible to add this 4k  site 

### ISSUE THREAD

**Issue by ShoaibKhanali** [phisher98/cloudstream-extensions-phisher#189]
### Source name

https://w1.uhdmovies.mom

### Source link

https://w1.uhdmovies.mom

### Source language

Multi 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
limited Content
