### ISSUE TITLE
Streamplay issue, tried to watch Avengers infinity war, video played Avengers endgame 😭

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/cloudstream-extensions-phisher#191]
### Source Name

Streamplay 

### Source language

Hindi 

### Steps to reproduce

Play Avenger infinity war in streamplay 

### Expected behavior

Avenger infinity war should be played

### Actual behavior

Avenger endgame movie played 

### CloudStream Version

Red ( latest) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
![Screenshot_2024-10-03-11-38-32-407_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/243bf573-4642-4882-b039-d634431b3d7e)
![Screenshot_2024-10-03-11-38-15-800_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/c12e6c72-5726-41bf-9dad-ee5957987e5e)
I'm not seeing any issues Send a video

**Comment by Krishna-art-dev** [comment]
https://filetransfer.io/data-package/59gDAYig#link

See half the recoding, you will find 2 different movies, in 2 different vega movies sources, on 1st and 2nd Avenger endgame is played, then on 3rd and 4th source Avenger infinity war is played 


Extra 
Got a bug idk what is is watch full recording to know ( cs3 bug ) or source issue idk I didn't check

**Comment by phisher98** [comment]
I think that could be any other sources giving that I don't want to change anything else it could impact other movies and shows

**Comment by Krishna-art-dev** [comment]
Oky no problem, I just informed you this problem exists you can close this

**Comment by phisher98** [comment]
Yeah but if i will try to get to root cause of this it could impact more movies or even doesn't even work Streamplay is very complex
