### ISSUE TITLE
Kdrama source extension

### ISSUE THREAD

**Issue by rebibeMee** [phisher98/cloudstream-extensions-phisher#192]
### Source name

goplay

### Source link

https://goplay.su/

### Source language

korean

### Other details

has an old kdrama with nice resolution and alot of mirror..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Captcha Protected
