### ISSUE TITLE
Anichi (Streamplay)

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/cloudstream-extensions-phisher#193]
### Source Name

Streamplay

### Source language

all

### Steps to reproduce

https://github.com/user-attachments/assets/0d5a2018-4eb7-4c38-9e67-a197cacda3ca

### Expected behavior

Play season 1

### Actual behavior

It seems that the newly added anichi is playing season 2 of 'The Promised Neverland' when season 1 is played.

### CloudStream Version

4.4.0 3a657d7 October 1, 2024 8:13:36 PM

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
I'm going to remove it if it's giving issues

**Comment by Rachitidk** [comment]
Hey, why don't you shift the anichi already present in rowdycado repo, which has stopped working because of lack of update.

**Comment by phisher98** [comment]
Check now
