### ISSUE TITLE
Moviesdrive issue in streamplay 

### ISSUE THREAD

**Issue by nguyenquocngu93** [phisher98/cloudstream-extensions-phisher#194]
### Details

Can't load any moviesdrive link (hubcloud, pixeldrain) at the moment, i don't know just me or everyone

Pls check it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Which Series/Movie ?

**Comment by nguyenquocngu93** [comment]
> Which Series/Movie ?

Any movie

**Comment by phisher98** [comment]
Its loading for me Working fine

**Comment by nguyenquocngu93** [comment]
> Its loading for me Working fine

But, but i don't see any, even with vpn and cloudfrare 

https://github.com/user-attachments/assets/2b6b83a6-5172-4caa-aa35-4b2561e2bd29

**Comment by nguyenquocngu93** [comment]
> Its loading for me Working fine

Hubcloud add cloudfrare.....


Bye bye TV shows with 4k lol
![Screenshot_2024-10-04-17-18-42-641_com android chrome](https://github.com/user-attachments/assets/68f683f7-e63c-4aeb-b01c-a4ce8b3c9111)
