### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Politecoder** [phisher98/cloudstream-extensions-phisher#195]
(Streamplay) one last bug I found is the same issue as it was there with movies4u, VegaMovies is loading all the episode links in one single episode, please fix it.
For example: Kota Factory season 3
![Screenshot_2024-10-04-19-42-45-958](https://github.com/user-attachments/assets/4c78a2d1-1318-4776-98f3-d8c12990a605)

**Comment by Politecoder** [comment]
Thanks a lot !

**Comment by nguyenquocngu93** [comment]
@phisher98 

So, I tried with the show he mentioned but I don't get any vcloud or pixeldrain 1080p
![Screenshot_2024-10-04-23-04-20-704_com dl lagradost cloudstream3](https://github.com/user-attachments/assets/e4125ff0-fcf4-48f8-9e09-b0202fe9f06f)


This is what i only get

Why this happened to only me, what should i do

**Comment by phisher98** [comment]
Reload links it's protected by Cloudflare so sometimes you need to reload links if it goes through

**Comment by phisher98** [comment]
Or try to change DNS on your router
