### ISSUE TITLE
Streamplay Subtitles And OVA

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/cloudstream-extensions-phisher#196]
### Source Name

Streamplay 

### Source language

all

### Steps to reproduce

1)Date a live season 2, episode 4 Subtitles problem
2)Season 0, episode 1.
3)Attack on Titan, ep 6 of season 4

### Expected behavior

1)Subitle should not be doubled.
2)Season 0 episode 1 should play ova.
3) Attack on Titan season 4, wrong season.

### Actual behavior

1)Subitle is doubled.
![1000106399](https://github.com/user-attachments/assets/906ed245-bc84-484a-abd6-62aca3dd05c3)

2)Season 0 episode 1, plays season 1 episode 1 instead of the ova.

3) Tried to see Attack on Titan season 4 episode 6 for fight, showed different ep/season (don't know which one) by all sources probably.

### CloudStream Version

Latest Red

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
1. SUBTITLE issue is not a extension issue 
2. OVA not supported 
3.  With the information provided not able to understand the issue.

**Comment by Rachitidk** [comment]
> 1. SUBTITLE issue is not a extension issue
> 
>     2. OVA not supported
> 
>     3. With the information provided not able to understand the issue.

3) Played other episodes or season instead of episode 6 of season 4 attack. ( Don't know which one as I didn't watch Attack on Titan)
