### ISSUE TITLE
Site request 

### ISSUE THREAD

**Issue by ShoaibKhanali** [phisher98/cloudstream-extensions-phisher#198]
### Source name

katmoviehd

### Source link

https://katmoviehd.fi

### Source language

Multi 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
https://github.com/SaurabhKaperwan/CSX

This source was added by dev and removed I guess you can ask them to add it back if they want to
