### ISSUE TITLE
Time4Tv not working

### ISSUE THREAD

**Issue by subby2006** [phisher98/cloudstream-extensions-phisher#199]
### Source Name

Time4tv

### Source language

English

### Steps to reproduce

Open any channel in the 24/7 channels category

### Expected behavior

Channels should play

### Actual behavior

All channels fail to play with error bad http status. You may need to update the referer as DaddyLive changes it frequently

### CloudStream Version

Red Icon version 4.4.0 build 15a27b4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
I can say it's somewhat a source issue or your ISP related 
![Screenshot_2024-10-08-08-35-49-859_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/ac3839d9-5300-4a9e-9999-231ab0798bb5)
![Screenshot_2024-10-08-08-34-43-148_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/882ee0b2-4591-4c61-8e74-5b824c152a7d)
