### ISSUE TITLE
Streamplay Improvement

### ISSUE THREAD

**Issue by Politecoder** [phisher98/cloudstream-extensions-phisher#201]
### Source Name

Vegamovies

### Source language

.

### Steps to reproduce

Whenever G-Direct link option shows first, it just loads G-Direct links and not loading the pixeldrain and v-cloud links, for example, Iron Man, Loki, etc. 
![Screenshot_2024-10-08-15-46-49-130](https://github.com/user-attachments/assets/12abfdc2-eea2-45c6-9c20-eb9e633b6270)
![Screenshot_2024-10-08-15-47-32-456](https://github.com/user-attachments/assets/72e45e6a-f6c5-4604-b6d6-e831dd2d5917)
In the above screenshot, it loads links for 2160p v-cloud links as the option is coming first but loads only GD links for 1080p even if the vcloud links are available.

### Expected behavior

Should load both GD and v-cloud irrespective of G-Direct links showing up first.
Thanks

### Actual behavior

.

### CloudStream Version

.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
which series ?

**Comment by Politecoder** [comment]
> which series ? NVM Got it

Loki

**Comment by Politecoder** [comment]
Thanks brother
