### ISSUE TITLE
Anime Dekho (VidStream) No Links Found

### ISSUE THREAD

**Issue by DestroyerBDT** [phisher98/cloudstream-extensions-phisher#202]
### Source Name

AnimeDekho (VidStream)

### Source language

Hindi

### Steps to reproduce

Play some content with **VidStream** source

### Expected behavior

The content should start playing

### Actual behavior

Gives the error **No Links Found**

### CloudStream Version

Latest beta

### Other details

Tested with only **VidStream source**
This issue happens frequently even after fixing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
![image](https://github.com/user-attachments/assets/1938fb08-97f7-4158-aafb-ccfaf64216d5)
