### ISSUE TITLE
Some source suggestions for streamplay lite 

### ISSUE THREAD

**Issue by sidrockzz98** [phisher98/cloudstream-extensions-phisher#203]
### Source name
It would also be awesome if drive links(pixel drain, hubcloud, etc) were not shown in streamplay lite like it used to be for sorastream. 

Vidbinge 
Heartive

### Source link

https://www.vidbinge.com/
https://heartive.pages.dev/

### Source language

Multi

### Other details

Scraper with multiple sources 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
1.vidbinge is a Scrapper like Streamplay so won't add it as most of its sources are in Streamplay
2.Its not a reliable source as its deployed on Vercel
