### ISSUE TITLE
Site Request 

### ISSUE THREAD

**Issue by OtakuVadER** [phisher98/cloudstream-extensions-phisher#206]
### Source name

Pahe

### Source link

https://pahe.ink/

### Source language

English 

### Other details

Good site with good quality please can you add it??

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Not a Great source to add most of links are for Mega and 720p
