### ISSUE TITLE
One Pace not working

### ISSUE THREAD

**Issue by OtakuVadER** [phisher98/cloudstream-extensions-phisher#210]
### Source Name

One Pace

### Source language

Eng

### Steps to reproduce

Choose any episode and hit play 

### Expected behavior

It should play that episode 

### Actual behavior

It doesn't play that episode but says no links found 

### CloudStream Version

4.4.0 15a27b4 

### Other details

Clicking webview shows error 404

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Screenshot or any screen recording ?

**Comment by phisher98** [comment]
Looks like its an issue with Source Try OnePace from Animedekho Extension it has more sources

**Comment by OtakuVadER** [comment]
Can you pleasee split one pace and anime dekho. Since I don't any other sources than ome pace which I won't even use. Pleaeee can youu??

**Comment by phisher98** [comment]
Okay I will look into it

**Comment by phisher98** [comment]
Added OnePace AD

**Comment by OtakuVadER** [comment]
Saw it thanks!
