### ISSUE TITLE
Animedekho - hindisubanime - onepace

### ISSUE THREAD

**Issue by garouthe** [phisher98/cloudstream-extensions-phisher#211]
### Source Name

Anime Dekho

### Source language

Hindi

### Steps to reproduce

1. OnePace: Stopped Working
(Keep Showing Retry connection) Open Any Arc

2. AnimeDekho: Working Fine - (Improve if you have time)
-> Open The Ancient Magus Bride -> Season Special Shows Last after other seasons on Website but shows first as season 0 on cloudstream so episode numbering goes wrong.
-> Dubbed content so show only Dub bagde on poster.
-> Can add Tamil and Telugu Category

3.HindiSubAnime: Working Fine - (Improve if you have time)
-> Open Boruto  -> Season Special Shows Last after other seasons on Website but shows first as season 0 on cloudstream so episode numbering goes wrong.
-> Subbed content so show only Sub bagde on poster.

### Expected behavior

.

### Actual behavior

.

### CloudStream Version

Pre - Red Icon

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
1. Fixed.
2. 
-> Open The Ancient Magus Bride -> Season Special Shows Last after other seasons on Website but shows first as season 0 on cloudstream so episode numbering goes wrong. 
Its like that only if there will be any Season which doesn't have any Season then it comes under Season 0 so ignore the number.

-> Dubbed content so show only Dub bagde on poster.
There was no Sub or Dub its Multi Language so I have removed status now.

-> Can add Tamil and Telugu Category
Added 

3.HindiSubAnime:
-> Open Boruto -> Season Special Shows Last after other seasons on Website but shows first as season 0 on cloudstream so episode numbering goes wrong.
Same as 1st pointer
-> Subbed content so show only Sub bagde on poster.
Removed Badge for this as well
