### ISSUE TITLE
India vs New Zealand test

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/cloudstream-extensions-phisher#213]
### Source name

idk

### Source link

idk

### Source language

Hindi

### Other details

Request to add India vs New Zealand test in hindi and english. Is it possible to add different angle provided by jiocinema, eg, captain pov, batter pov, wicketkeeper pov as track in same source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
If you want to get something added 
Kindly ask before it starts live so I can get a heads up 

Is it still streaming ? Then reopen this issue

**Comment by Rachitidk** [comment]
> If you want to get something added Kindly ask before it starts live so I can get a heads up

Ys the did open the issue before match began.

> Is it still streaming ? Then reopen this issue

Yes, today was the first day, got dismissed due to rain, it's a three match series.

**Comment by Rachitidk** [comment]
Reopen the issue biroooo @phisher98

**Comment by phisher98** [comment]
Download QuickIPTV and use SportsIPTV to watch and let me know how it works 
![Screenshot_2024-10-17-09-26-53-131_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/28992629-e3d8-4a50-bdbe-b250a4e083cd)

**Comment by phisher98** [comment]
Added In IPTV player Sports Category Thumbnail is different but titles are correct check it
![Screenshot_2024-10-17-09-37-07-174_com lagradost cloudstream3 prerelease-edit](https://github.com/user-attachments/assets/2a49dbed-8b15-495a-b7b0-9ddfb171f28e)

**Comment by Rachitidk** [comment]
Nice it's working but, isn't there any way to get a permanent link, instead for every match. Is it possible to scrap from app such as cricfy tv
![1000108994](https://github.com/user-attachments/assets/85dbaeac-f473-4ee7-875e-bad573327ae9)
Or HDstreamz etc. 
I know a few site but they don't provide hindi language. E.g.
https://watch.cricstream.me
https://www.livecricketstreaming.cc / https://www.worldcupfree.com @phisher98

**Comment by phisher98** [comment]
Not possible at the moment maybe in future

**Comment by Rachitidk** [comment]
![1000109086](https://github.com/user-attachments/assets/da489162-e734-4f52-8081-8667142d31dc)
Can u upgrade the provider to 1080p and hindi if possible in IPTV. @phisher98
