### ISSUE TITLE
Time4tv is not stable anymore

### ISSUE THREAD

**Issue by Mrunknow3** [phisher98/cloudstream-extensions-phisher#215]
### Source Name

Time4tv

### Source language

English

### Steps to reproduce

Open time4tv
Click on any channels like barca spain
Comes error

### Expected behavior

Open time4tv 
Click anyone channel like barca spain
Open live barca spain channel

### Actual behavior

Not working any channels 

### CloudStream Version

Red icon

### Other details

You can add any stable website if you know i found this 
https://drmlive.in/
https://soccerlive.app/

Sometimes time4tv showing porn. 
Wrong sports channels. 
Now not working. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
It's working for me and source is quite unstable can't do anything about it

**Comment by Krishna-art-dev** [comment]
What about https://streamed.su/ 
This site provides api for there stream also 
Streams are stable 
A lot of sports category

**Comment by Mrunknow3** [comment]
Ok
