### ISSUE TITLE
Plus Fifa

### ISSUE THREAD

**Issue by Mrunknow3** [phisher98/cloudstream-extensions-phisher#216]
### Source name

Plus Fifa

### Source link

https://www.plus.fifa.com/en/?gl=in

### Source language

English

### Other details

They have all world Cup replays and they have some good football documentarys and it's free. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
No from my end
