### ISSUE TITLE
Site request 

### ISSUE THREAD

**Issue by ShoaibKhanali** [phisher98/cloudstream-extensions-phisher#218]
### Source name

starkflix.cloud

### Source link

https://scloud.starkflix.cloud

### Source language

Multi 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by Rachitidk** [comment]
Cloudflare protected, not possible.

**Comment by Rachitidk** [comment]
How do you all find this type of amazing site, btw?

**Comment by ShoaibKhanali** [comment]
It is not cloudflare protection

**Comment by ShoaibKhanali** [comment]
https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/video/#wiki_.25BA_download_sites here you can find all site

**Comment by Rachitidk** [comment]
> It is not cloudflare protection

It is

https://github.com/user-attachments/assets/d0979a42-a9c6-413f-95a6-d123f388e907

**Comment by Rachitidk** [comment]
> https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/video/#wiki_.25BA_download_sites here you can find all site
I didn't find this specific site over there.

**Comment by phisher98** [comment]
Yes it's Cloudflare protected also tried to bypass it but it will be a hot and miss scenario 

Reopen again if they remove Cloudflare

**Comment by Politecoder** [comment]
Bro they have removed cloudflare

**Comment by Politecoder** [comment]
Please do add it separately too in repository
