### ISSUE TITLE
Add These Movie Sites 

### ISSUE THREAD

**Issue by Zafor7869** [phisher98/cloudstream-extensions-phisher#219]
### Details

https://ssrmovies.app/
https://fibwatch.lol/
https://katmoviehd.fi/

Bro, please add these movie sites in your extensions. 

![Screenshot_20241018_061949](https://github.com/user-attachments/assets/0a4080d6-be55-4c52-a2e8-7ac3b867f96e)
![Screenshot_20241018_061956](https://github.com/user-attachments/assets/c6733b07-0f55-4583-9977-41f071049f36)
![Screenshot_20241018_062016](https://github.com/user-attachments/assets/bcfcdd84-97c7-4c61-9822-01b8224237ae)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by rockhero1234** [comment]
Not able to extract streaming link from these. So no
