### ISSUE TITLE
Live stream

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/cloudstream-extensions-phisher#220]
### Source name

Tflix

### Source link

https://tv.tflix.app

### Source language

All

### Other details

There's 1 more site https://nowmesport.com
I don't know about cloudflare protection.
Best regards.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by rockhero1234** [comment]
nowmesport is of mhdtv I think phisher got DMCA so he removed that

**Comment by phisher98** [comment]
nowmesport is very dynamic and keeps on changing domains so its hard to keep up with them 

This will not be added  and as for tflix App having issues with playing DRM content for some sources can't be added
