### ISSUE TITLE
No trending thumbnails and two instances of StreamPlay-Lite

### ISSUE THREAD

**Issue by mpaunovic** [phisher98/cloudstream-extensions-phisher#223]
### Details

As of yesterday on the homepage there are no thumbnails for the trending column. Also, when choosing a provider for the homepage there are two StreamPlay-Lite options. I was wondering if anybody else could reproduce the issues?

Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
This issue is from TMDB API 

We have to ait till it gets fixed
