### ISSUE TITLE
One Pace not working!

### ISSUE THREAD

**Issue by OtakuVadER** [phisher98/cloudstream-extensions-phisher#227]
### Source Name

One Pace

### Source language

English 

### Steps to reproduce

Select extension 

### Expected behavior

Show home page and work

### Actual behavior

Shows retry connection

### CloudStream Version

4.4.0 217cf41 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Screenshot plz

**Comment by OtakuVadER** [comment]
https://ibb.co/FxJNDyy
