### ISSUE TITLE
Anime Dekho is not working well

### ISSUE THREAD

**Issue by HaxerAhmed** [phisher98/cloudstream-extensions-phisher#229]
So many time Anime dekho cant load even i tried vpn and also changed dns but didn’t work. If i delete the source and re download it then its work. Again after some days it again cant load and everytime i have to repeat the delete and re download process. I am using pre version red colour icon. Is u have any permanent solution?

**Comment by phisher98** [comment]
I'm not able to reproduce this issue

**Comment by phisher98** [comment]
Screen record it to check further if I can find the issue

**Comment by HaxerAhmed** [comment]
![Screenshot_2024-10-26-14-31-59-294_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/9ce2f0ad-d4ad-4c2b-9f0f-efa703d81050)

**Comment by phisher98** [comment]
I think you have downloaded Animedekho from Hex Repo.


Remove it and download again from Phisher Repo
