### ISSUE TITLE
Add recently updated anilist section in streamplay 

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/cloudstream-extensions-phisher#230]
### Details

![Screenshot_2024-10-26-16-49-05-68_8090ff421eb8a7caaa4bac331120a211](https://github.com/user-attachments/assets/e3fd297c-79df-41b8-b5f6-7a6285d5b670)
Am talking about this section 

Recently updated ( I want this )

Optional 
1. Trending movies
2. Top rated 
3. Most favourite 
4. Popular anime 
5. Recommend shows 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Streamplay uses TMDB not Anilist for catalog

**Comment by Krishna-art-dev** [comment]
> Streamplay uses TMDB not Anilist for catalog Whats the source of this screenshot

Dantotsu app

**Comment by phisher98** [comment]
I don't think its possible or Its a Skill issue 

Unable to fulfill this
