### ISSUE TITLE
Live TV

### ISSUE THREAD

**Issue by Moviellect** [phisher98/cloudstream-extensions-phisher#232]
### Source name

Jio TV

### Source link

_---------

### Source language

Hindi

### Other details

Sir please restart the Indian TV(jio tv) extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Source is down so it wont work anymore
