### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by Moviellect** [phisher98/cloudstream-extensions-phisher#233]
### Source name

9xflix

### Source link

https://9xflix.cc/

### Source language

Dual Audio

### Other details

Sir this is a old and trustworthy website. Sir please add this website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
We already have better Hindi Sources why do you want it to be added ? 

Check out Movierulzhd and HDmovies2,22 and Streamplay.

Better then [9xflix.cc/]
