### ISSUE TITLE
A torrent(magnet link) site

### ISSUE THREAD

**Issue by Moviellect** [phisher98/cloudstream-extensions-phisher#236]
### Source name

---------------------

### Source link

--------------------

### Source language

--------------------

### Other details

As we know in the new prerelease of cloudstream we can stream magnet links. Sir, I want you to add such a site in your repository which provides magnet link. By doing this the video will stream through the magnet link.
🙏🙏🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by Moviellect** [comment]
What is this "Moviellect assigned phisher98"
I don't know but it say I assigned.

**Comment by phisher98** [comment]
Torrent is still in beta phase till then use Stremio it provides same content for any query ping in support for more information
