### ISSUE TITLE
pinoymoviepedia

### ISSUE THREAD

**Issue by rebibeMee** [phisher98/cloudstream-extensions-phisher#238]
### Source name

pinoymoviepedia

### Source link

https://pinoymoviepedia.ru/

### Source language

Filipino, English

### Other details

ty bro 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Development in progress

**Comment by phisher98** [comment]
Added

**Comment by rebibeMee** [comment]
thank you very much 😇🫡
