### ISSUE TITLE
Streamplay subtitles

### ISSUE THREAD

**Issue by nguyenquocngu93** [phisher98/cloudstream-extensions-phisher#239]
### Details

Hi, can you support Vietnamese subtitle auto load in streamplay,
Example: movie "the wild robot",  when i check on opensubtitles and subdl there are Vietnamese subtitles for this movie but your Streamplay load about 30+ language but not my language 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
It's not a extension issue but you can use following method to load subtitles

1. Select Source and then Select Load from Internet 
2. Select Filter icon and select your language 
3. Search and then load 
![Screenshot_2024-11-05-22-53-10-861_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/fd46ed33-ff3a-48eb-8e50-57907c35ad3d)
![IMG_20241105_225359](https://github.com/user-attachments/assets/173e30d6-fa42-412e-b02f-00d605f239a8)
![Screenshot_2024-11-05-22-52-47-535_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/9ae1db19-6e27-476c-a256-cb864e92a0f4)

**Comment by phisher98** [comment]
@nguyenquocngu93 Added more Subtitle Support in Streamplay Now it has Many Lang including yours

**Comment by nguyenquocngu93** [comment]
> @nguyenquocngu93 Added more Subtitle Support in Streamplay Now it has Many Lang including yours

Oh, Thank you!
