### ISSUE TITLE
Multimovies is back

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/cloudstream-extensions-phisher#240]
### Source Name

Multimovies, Streamplay 

### Source language

Hindi

### Steps to reproduce

N/A

### Expected behavior

Should work 

### Actual behavior

Not working 

### CloudStream Version

Latest 

### Other details

multimovies.bond

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
It's a source issue I have checked Multi is not stable as of now when It loads Streamplay also loads multi movies.

No issue in Extension

**Comment by Rachitidk** [comment]
What about its sperate extension? @phisher98

**Comment by phisher98** [comment]
Working fine as well

**Comment by Rachitidk** [comment]
Yesterday it wasn't for me

**Comment by phisher98** [comment]
That's what I am saying Source is not stable as of now
