### ISSUE TITLE
Animedekho Vidstream Server Fix

### ISSUE THREAD

**Issue by garouthe** [phisher98/cloudstream-extensions-phisher#243]
### Source Name

Anime Dekho

### Source language

Hindi

### Steps to reproduce

Try Playing Any Episode or Movie

### Expected behavior

VidStream Source Should be Shown

### Actual behavior

VidStream Source Not Showing

### CloudStream Version

Pre - Red Icon

### Other details

happens for HindiSubAnime and One Pace AD also

many old shows have this server only

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Fixed

**Comment by garouthe** [comment]
its not fixed @phisher98

**Comment by phisher98** [comment]
Source changed encryption method may not be fixed for a long time now
