### ISSUE TITLE
Dramafull

### ISSUE THREAD

**Issue by rebibeMee** [phisher98/cloudstream-extensions-phisher#244]
### Source name

Dramafull

### Source link

https://dramafull.net/

### Source language

English, Chinese, Korean, Japanese, Filipino

### Other details

Has large variety of asian drama and movies mostly 720p

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Its Search will not work complex

**Comment by rebibeMee** [comment]
tried it seem search has problem
