### ISSUE TITLE
Content of Netflix

### ISSUE THREAD

**Issue by Moviellect** [phisher98/cloudstream-extensions-phisher#246]
### Source name

Net3lix

### Source link

https://net3lix.world/

### Source language

---

### Other details

Sir Please add this website is very fast with multiple resources link and quality 🙏 

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Its basically scraping other website which is scraping other website (Multiple) 

VidBinge 

Unable to add as it needs an API key
