### ISSUE TITLE
Bollyzone not working

### ISSUE THREAD

**Issue by devanshuagarwal667** [phisher98/cloudstream-extensions-phisher#247]
### Details

Hello,

I would like to inform you that the bollyzone.tv inside desicinema repository has been changed to bollyzone.to. Kindly update the code as it has been a month since the last update.

Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
#248

**Comment by devanshuagarwal667** [comment]
Can you add tvlogy strean too in bollyzone i think it is in desicinema and still using old bollyzone.tv
