### ISSUE TITLE
Onepace Error

### ISSUE THREAD

**Issue by akshit-21** [phisher98/cloudstream-extensions-phisher#249]
### Source Name

Onepace

### Source language

English 

### Steps to reproduce

Error loading Onepace 
![Screenshot_2024-11-17-15-05-11-259_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/dee4539f-1f19-4e3e-b95b-40ed34b5926c)

### Expected behavior

Should Work.

### Actual behavior

Isn't Working 

### CloudStream Version

Red One -4.4.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Use Onepace AD from same Extension

This source keeps changing and Links don't work most of times 

Try Alternative

**Comment by phisher98** [comment]
<img width="877" alt="image" src="https://github.com/user-attachments/assets/e118d1a9-0eb0-495d-a2d0-26573a70f3d4">
Working fine source is down for Link playing 
Try Onepace AD
<img width="890" alt="image" src="https://github.com/user-attachments/assets/f613a1d9-22e2-4c80-9b19-643cf4b8b41e">
Its Working

**Comment by akshit-21** [comment]
Then can you remove it from animedekho

**Comment by phisher98** [comment]
Its present in Onepace separately with name Onepace AD  as as well you don't need to download Animedekho
