### ISSUE TITLE
add YTS MX

### ISSUE THREAD

**Issue by OtakuArab** [phisher98/cloudstream-extensions-phisher#252]
### Details

https://yts.mx

It has more than one video quality.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Example?

**Comment by OtakuArab** [comment]
> Example?
> 
> Screenshot
https://yts.mx
![Screenshot_٢٠٢٤-١١-١٨-١٤-٣١-٤٣-٠٩٢_com android chrome-edit](https://github.com/user-attachments/assets/baf81774-595c-44be-a7ab-eafba3e23bc3)

This added site has only three qualities.
![Screenshot_٢٠٢٤-١١-١٨-١٤-٣٤-٠٣-٠٤٠_com android chrome](https://github.com/user-attachments/assets/155f83f0-de8b-4877-a4fb-05bb80371282)

**Comment by OtakuArab** [comment]
and you https://yts.mx
![Screenshot_٢٠٢٤-١١-١٨-١٤-٤٤-٥٤-٩٩٩_com android chrome-edit](https://github.com/user-attachments/assets/e8d56011-6b28-4f44-84ce-a4da28de360c)
![Screenshot_٢٠٢٤-١١-١٨-١٤-٤٦-١٦-٧٤٢_com android chrome-edit](https://github.com/user-attachments/assets/32652a16-6f55-4e3a-abc3-4b34428f0156)

**Comment by phisher98** [comment]
Source is down

**Comment by phisher98** [comment]
Added under YTS use VPN if not working
