### ISSUE TITLE
add showbox

### ISSUE THREAD

**Issue by OtakuArab** [phisher98/cloudstream-extensions-phisher#253]
### Details

https://www.showbox.media

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by rockhero1234** [comment]
Why you need this?

**Comment by OtakuArab** [comment]
> Why you need this?

Because the size is lower than 1080 quality, the episode size may be 500 MB.

**Comment by OtakuArab** [comment]
> > Why you need this?
> 
> Because the size is lower than 1080 quality, the episode size may be 500 MB.

I have previously downloaded episodes of the Game of Thrones series, each episode in size of 500 MB, via the Anomi application, but the source changed the link and the problem has not been solved yet. I have downloaded more than one series in a smaller size with 1080 quality.
![Screenshot_٢٠٢٤-١١-١٨-١٥-٥٩-٤٨-٥٠٧_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/8bd14792-05b9-4432-8c8e-b1c17f07019d)
![Screenshot_٢٠٢٤-١١-١٨-١٥-٥٩-٥٣-٠٤٣_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/29594436-d57a-429f-b295-53e97a664e93)
![Screenshot_٢٠٢٤-١١-١٨-١٥-٥٩-٥٨-٦٤٣_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/f21259c4-8c04-4d0f-8ad5-52b852e166dd)
