### ISSUE TITLE
Missing thumbnails 

### ISSUE THREAD

**Issue by Jamess661** [phisher98/cloudstream-extensions-phisher#254]
### Source Name

Uhdmovies 

### Source language

English 

### Steps to reproduce

Just  search for content 

### Expected behavior

Expected all thumbnails 

### Actual behavior

Missing thumbnails 

### CloudStream Version

Red version 

### Other details

![1000119025](https://github.com/user-attachments/assets/09aca8a5-d886-4d61-a1b2-fe3750ebf64d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Working fine 
![Screenshot_2024-11-19-10-56-31-842_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/ad6b203e-0adb-4675-ad89-92a32bbd05c2)
