### ISSUE TITLE
Asian Dramas Best Source

### ISSUE THREAD

**Issue by akshit-21** [phisher98/cloudstream-extensions-phisher#257]
### Source name

Dramaday

### Source link

https://dramaday.me

### Source language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
already added in Streamplay

**Comment by akshit-21** [comment]
Is it possible to do separately

**Comment by phisher98** [comment]
No we already have Dramacool and AsianHD better sources

**Comment by akshit-21** [comment]
Problem in these comes with subtitles, sometime we need to zoom to get rid of blackbars then subtitles are cropped.
