### ISSUE TITLE
English Source SFlix Clone

### ISSUE THREAD

**Issue by akshit-21** [phisher98/cloudstream-extensions-phisher#258]
### Source name

Dopebox

### Source link

https://dopebox.to/home

### Source language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Extractor is broken Can't be added yet

**Comment by akshit-21** [comment]
Ok
