### ISSUE TITLE
How about this One ?

### ISSUE THREAD

**Issue by akshit-21** [phisher98/cloudstream-extensions-phisher#262]
### Source name

Katdrama

### Source link

https://katdrama.com/

### Source language

Hindi

### Other details

Kdrama Hindi Dubbed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
It's very dynamic in nature and it's also Downloading Links
