### ISSUE TITLE
Slight Improvement (Streamplay)

### ISSUE THREAD

**Issue by Politecoder** [phisher98/cloudstream-extensions-phisher#265]
![Screenshot_2024-11-19-22-22-58-215](https://github.com/user-attachments/assets/4bd3c0f4-92bf-4442-b06d-e05b1745e4e7)
It will be convenient if the vcloud and pixeldrain links also showed the file size just like MoviesDrive links.
Thanks

**Comment by Politecoder** [comment]
One more thing, is it possible to add Hdmovie2 too in streamplay ?

**Comment by phisher98** [comment]
It's dynamic — sometimes it gets extracted from the source, and other times it doesn't. I believe the separate extension for Hdmovie2 is the best option, as it reduces the load on devices and ensures that all sources are loaded correctly

**Comment by Politecoder** [comment]
> It's dynamic — sometimes it gets extracted from the source, and other times it doesn't. I believe the separate extension for Hdmovie2 is the best option, as it reduces the load on devices and ensures that all sources are loaded correctly

No issues
