### ISSUE TITLE
Is this source possible to add 

### ISSUE THREAD

**Issue by Uvdon** [phisher98/cloudstream-extensions-phisher#268]
### Source name

Alpha

### Source link

https://broflix.cc/search

### Source language

English 

### Other details

There's this great website- https://broflix.cc/search and I was wondering if it's possible to add the Alpha server from ad free sources (not really sure what's the real name of the server) and or server XYZ (vidsrc) from ad sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by Uvdon** [comment]
I had no ads btw cuz I was using ad blocker. Idk if that matters cuz I'm not a coder

**Comment by phisher98** [comment]
Its Highest Quality is mostly 720p and its scraping from other websites 

Most of sources already available in Streamplay

**Comment by Uvdon** [comment]
Ok thanks

**Comment by Uvdon** [comment]
But it doesn't have series like SpongeBob, Simpsons, monk etc
