### ISSUE TITLE
Please add Live T.v

### ISSUE THREAD

**Issue by Kira0116** [phisher98/cloudstream-extensions-phisher#270]
### Source name

Crichd , Neeplay

### Source link

https://neeplay.com/. https://crichd.com.co/crichd29112024

### Source language

All

### Other details

Please add these sites if you can especially needed for sports 😭🙏.
Both existing crichd and nowmetv are not working 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by Kira0116** [comment]
Best for All sports - https://en12.sportplus.live/

**Comment by phisher98** [comment]
No Live Extensions as they are very dynamic which is complex to keep up with changes
