### ISSUE TITLE
Request to add 

### ISSUE THREAD

**Issue by Zafor7869** [phisher98/cloudstream-extensions-phisher#271]
### Details

https://onlykdrama.online/

In this website has available lots of korean dramas with english subtitles and dub. If possible please add it, it's a humble request brother. 

![Screenshot_20241203_215440](https://github.com/user-attachments/assets/df4f261b-580d-4cd0-bafd-9af89f8c3129)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Source is very Dynamic not good for streaming and extracting
