### ISSUE TITLE
Please add server from Vega app (https://github.com/Zenda-Cross/vega-app)

### ISSUE THREAD

**Issue by Uvdon** [phisher98/cloudstream-extensions-phisher#272]
### Source name

Tom

### Source link

https://github.com/Zenda-Cross/vega-app

### Source language

Hindi English 

### Other details

So their is an app called (vaga-app)- https://github.com/Zenda-Cross/vega-app. Which is open source and like cloud stream. It has a very nice provider called multi stream with server called Tom. It plays several tv shows like family guy and the walking dead fine without user limitations and vpn, which cloud stream plugins has issues with. I know you don't like adding new servers but I was wondering if you can add this provider it will be very much helpful for all of us. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Do you want me to add it to Streamplay ?

**Comment by Uvdon** [comment]
Yes please

**Comment by Uvdon** [comment]
You are correct, it's not working. But I promise it was working just fine for the past 2 weeks I was using it. Maybe it's not a good server after all. It's all good no need to add this server. Thank you I very much appreciate you anyway.

**Comment by phisher98** [comment]
Yup we can reopen if it gets Fixed

**Comment by Uvdon** [comment]
The server is back would you be able to add it plz. Thank you

**Comment by phisher98** [comment]
Added if you don't see Tom source it could mean 2 things either other source added it so it will not duplicate add it and second tom doesn't have that content

**Comment by Uvdon** [comment]
Ok
