### ISSUE TITLE
Add Tv Series session on Pencurimovie Plugin.

### ISSUE THREAD

**Issue by Sudiar31** [phisher98/cloudstream-extensions-phisher#273]
Please Add TV series Session on Pencurimovie Plugin.
Thanks

**Comment by Sudiar31** [comment]
Thanks very much Bro.
I am very appreciated for your work.

Sorry for my English

I am indonesian

**Comment by phisher98** [comment]
No issues

**Comment by Sudiar31** [comment]
Thanks a lot.
