### ISSUE TITLE
Please add this site : Donghuastream 

### ISSUE THREAD

**Issue by VasuRakholiya** [phisher98/cloudstream-extensions-phisher#274]
### Source name

Donghuastream 

### Source link

https://donghuastream.org/

### Source language

English 

### Other details

although it doesn’t have a large library they release a lot of 4K titles that are subbed and they carry certain 4K releases that are unique to them that I can’t find elsewhere.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Added
