### ISSUE TITLE
Topstreamfilm

### ISSUE THREAD

**Issue by sonkoko** [phisher98/cloudstream-extensions-phisher#275]
### Source name

Topstreamfilm

### Source link

https://www.topstreamfilm.live/

### Source language

German

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Added

**Comment by sonkoko** [comment]
Thank you so much 👍
