### ISSUE TITLE
Can you please add Kissasian to your repo 

### ISSUE THREAD

**Issue by Revenir01** [phisher98/cloudstream-extensions-phisher#276]
### Source name

Kissasian

### Source link

https://kisasia.cam/

### Source language

Various Asian 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by Revenir01** [comment]
With Dramacool, now being non functional, if possible this might also be a good alternative to add to your repo.

**Comment by phisher98** [comment]
I understand what are you trying to say but its just another clone of Drama cool and its getting sources from AsianHD and Kisssh which are already available I want to add best Sources only to the repo not temp ones 

Rejecting this one
