### ISSUE TITLE
Subtitles appearing strange using KissKh

### ISSUE THREAD

**Issue by Revenir01** [phisher98/cloudstream-extensions-phisher#277]
### Details

Subtitles on a lot of content using KissKh from your repo seem to come up with random letters, numbers and symbols, I'm not sure if it's some kind of encoding issue from cloudstream, but when I check the same content directly on the KissKh website, subtitles display normally, I have attached an image of what they look like via cloudstream and kisskh
![unknown](https://github.com/user-attachments/assets/8f7e14c9-e714-40e4-b531-3ffda5c447b5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Yup it's a known issue it's encrypted from the source which is complex to decode and then load we can't do anything about it right now

**Comment by katekh70** [comment]
Seems to be happening again. Shows such as **Affinity**, **This Is the Feeling Of Love**, **Love Between Lines** (from ep. 25) notably have the same sort of subtitle issue that was present here. Hoping this could be figured out again soon!

**Comment by phisher98** [comment]
It got broken in recent app update use stable version for now
