### ISSUE TITLE
 Can You add this  anime source 

### ISSUE THREAD

**Issue by Fishman999** [phisher98/cloudstream-extensions-phisher#278]
### Source name

Aniwatchtv

### Source link

https://aniwatchtv.to/home

### Source language

English and Japanese 

### Other details

Hello sir can You add this source in Your Phisher repo Collection because animepahe doesn't have lot of collection of old anime and dub anime 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Its a clone of Hianime which is busted as of now because of change in there encryption 

Closing this
