### ISSUE TITLE
Can you please add Burning-Series

### ISSUE THREAD

**Issue by xdoperr** [phisher98/cloudstream-extensions-phisher#284]
### Source name

Burning-Series

### Source link

https://bs.to/

### Source language

German

### Other details

Hello can you please add Burning Series? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Source doesn't look so promising and content is limited

**Comment by xdoperr** [comment]
Really? There are some good sites in germany and bs.to is just one of them. But hey it's ok if you don't want to add the page, thanks for your work anyway. I appreciate your good work !💯

**Comment by phisher98** [comment]
Source will not have any posters on homepage and will look a Little ugly compare to other Ext
