### ISSUE TITLE
Can This Source Be Added ?

### ISSUE THREAD

**Issue by akshit-21** [phisher98/cloudstream-extensions-phisher#287]
### Source name

Desi Tellu Box

### Source link

https://www.desitellybox.net/

### Source language

Hindi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
We already have this under Desicinemas with Name Bollyzone

**Comment by akshit-21** [comment]
No it's different bollyzone only provides 480p.

**Comment by akshit-21** [comment]
https://desirulez.net/

You can add this one.
This one also has atleast 720p.
