### ISSUE TITLE
Add This Anime Source 

### ISSUE THREAD

**Issue by Fishman999** [phisher98/cloudstream-extensions-phisher#291]
### Source name

Kickass anime

### Source link

https://www1.kickassanime.mx/

### Source language

English & Japanese 

### Other details

Hello sir this source doesn't scrape from any other websites its a good one source please include this it has a large anime database

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
It only have  1 source

**Comment by Fishman999** [comment]
> It only have 1 source

There are 2 sources  Vid and Bird plus it hosts their own Anime please make a repo on it sir

**Comment by phisher98** [comment]
No Most of it has 1 source only

**Comment by Fishman999** [comment]
Most of the website don't work anymore, some of them not uploading episodes sir...
its last one standing website if You create a repo of this it will act as a Great Backup in your Collection rest of it is Your decision 
Thanks

**Comment by phisher98** [comment]
Buddy Hianime,Allanime and Ankita is Still working and I'm using it


I will check once I get time for this

**Comment by Fishman999** [comment]
Thank you for considering this website. I appreciate your time. I Have a little suggestion for you if you will work on this repo please add multiple URLs of this Website As Backup written on their website..

Once again thank you sir

**Comment by phisher98** [comment]
No This source was cracked by Aniyomi so I was able to add it won't be making any changes for a while as it's complex
