### ISSUE TITLE
Please add this website if possible

### ISSUE THREAD

**Issue by ShoaibKhanali** [phisher98/cloudstream-extensions-phisher#294]
### Source name

protonmovies

### Source link

https://protonmovies.xyz/

### Source language

Multi 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Not possible to add it as its redirecting to download links on hosting's which have Cloudflare protection
