### ISSUE TITLE
Anime website

### ISSUE THREAD

**Issue by HaxerAhmed** [phisher98/cloudstream-extensions-phisher#296]
### Source name

Crunchyroll

### Source link

https://www.crunchyroll.com

### Source language

So many language

### Other details

Good for anime watching its provide English hindi and all kind of language what release a anime

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Reject
