### ISSUE TITLE
Please add if possible

### ISSUE THREAD

**Issue by Zockerwolf76** [phisher98/cloudstream-extensions-phisher#297]
### Source name

Aniworld

### Source link

https://aniworld.to/

### Source language

German

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Its already available in Hex Repo you didn't read the pointers and created the Request 

Before any Request check each repo
