### ISSUE TITLE
Please fix this

### ISSUE THREAD

**Issue by Kira0116** [phisher98/cloudstream-extensions-phisher#303]
### Source Name

Toonstream , Animedekho

### Source language

Multi

### Steps to reproduce

It showing "no links found' especially old cartoons.... please fix this 🥺😭

### Expected behavior

Not playing links

### Actual behavior

Playing links

### CloudStream Version

Beta

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Can't be fixed as Extractor as busted as of now try Anime world
