### ISSUE TITLE
Multi Audio Source

### ISSUE THREAD

**Issue by akshit-21** [phisher98/cloudstream-extensions-phisher#307]
### Source name

NoxTv

### Source link

https://noxtv.site/

### Source language

Hindi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Already available in Stream play Fixed it
