### ISSUE TITLE
Iptv player

### ISSUE THREAD

**Issue by Mrunknow3** [phisher98/cloudstream-extensions-phisher#308]
### Source Name

IPTV player

### Source language

Multi 

### Steps to reproduce

1. IPTV player clone and add m3u link 
2. M3u showing and video working
3. But after timeline and timeline not go ahed 
4. Not working like live stream player work

### Expected behavior

1. IPTV player clone and add m3u link 
2. M3u showing and video working
3. Work like live stream IPTV player works

### Actual behavior

1. IPTV player clone and add m3u link 
2. M3u showing and video working
3. But after timeline and timeline not go ahed 
4. Not working like live stream player work

### CloudStream Version

4.4.1 pre release

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Its not a Bug it all depends on list you provide it could only play m3u8 links
